{
	"Target": {
		"EntitySet": "Images",
		"ReadLink": "{@odata.readLink}",
		"Service": "/MirataFormsCoreComponents/Services/MirataAPI.service"
	},
	"_Type": "Action.Type.ODataService.DownloadMedia"
}